server:
  port: 8080
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: admin1
    key-store-type: JKS

jwt:
  secret: secret_example
  lifetime: 60m

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jwt_db
    username: admin
    password: admin
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  main:
    allow-circular-references: true
